### PR TITLE
fix/utf8_encode_deprication - Fix utf8_encode deprecation

### PR DESCRIPTION
**Pull request by abdalasif**
Fix utf8_encode deprecation notice for php 8.2+

### CODE REVIEW

**Comment by abdalasif** [comment]
@adohertyTS any chance this can be reviewed?

**Comment by adohertyTS** [comment]
hi @abdalasif , I've created a ticket for this internally here at Telesign. Could you tell me more about the impact this is having on you? That will help me prioritize the issue against our other work.

**Comment by abdalasif** [comment]
@adohertyTS thank you, this throws a warning on authentication as utf8_encode is used which is deprecated

**Comment by ralfzeit** [comment]
Hi @adohertyTS , when you can expect to apply these changes?

**Comment by adohertyTS** [comment]
Hi @ralfzeit , we are in-progress working on this issue, and if all goes well I would tentatively expect this issue to be fixed by Oct 31. Note that we do not currently accept external pull requests, so our developers would address this issue with a new, internal pull request.

**Comment by adohertyTS** [comment]
Hi @ralfzeit, I believe this most recent commit from Telesign fixes the issue:
https://github.com/TeleSign/php_telesign/commit/bba72a9064196e8692cd2eb0b75bddaabc86899b

I will close this PR out for now, but please open an issue on the repo if you run into any further trouble.

**Pull request closed without merging**
